insert into resources (title, url, description, img_url, created_by) values ('Intro to Cell Structure Video', 'https://www.youtube.com/watch?v=vwAJ8ByQH2U', 'This biology video tutorial provides a basic introduction into cell structure. It also discusses the functions of organelles such as the nucleus, ribosomes, mitochondria, chloroplasts, etc.', 'https://i.ytimg.com/vi/vwAJ8ByQH2U/maxresdefault.jpg', 1 );
insert into resources (title, url, description, img_url, created_by) values ('Crash Course in Mitosis', 'https://www.youtube.com/watch?v=L0k-enzoeOM', 'Hank describes mitosis and cytokinesis - the series of processes our cells go through to divide into two identical copies.', 'https://i.ytimg.com/vi/L0k-enzoeOM/maxresdefault.jpg', 1 );
insert into resources (title, url, description, img_url, created_by) values ('The Chemical Structure of DNA', 'https://www.compoundchem.com/2015/03/24/dna/', 'Image outline the general structure of DNA and an article including an incredibly useful simple overview of the process of protein synthesis from DNA', 'https://i1.wp.com/www.compoundchem.com/wp-content/uploads/2015/03/The-Chemical-Structures-of-DNA-RNA-Aug-2018.png?fit=1200%2C848&ssl=1', 2);
insert into resources (title, url, description, img_url, created_by) values ('Dynamic Periodic Table', 'https://ptable.com/', 'Interactive periodic table with dynamic layouts showing names, electrons, oxidation, trend visualization, orbitals, isotopes, and compound search.', 'Interactive periodic table with dynamic layouts showing names, electrons, oxidation, trend visualization, orbitals, isotopes, and compound search.', 3);
insert into resources (title, url, description, img_url, created_by) values ('Git Cheat Sheet', 'http://rogerdudler.github.io/git-guide/files/git_cheat_sheet.pdf', 'Quick reference for when you forget how to do basic git commands (aka all the time!!!)', 'https://image.slidesharecdn.com/gitcheatsheet-131205141010-phpapp02/95/git-cheat-sheet-1-638.jpg?cb=1386252637', 5);
insert into resources (title, url, description, img_url, created_by) values ('jQuery Cheat Sheet', 'https://htmlcheatsheet.com/jquery/', 'jQuery Cheat Sheet will help you create the code for animations, various effects and other features for your website. Find the most common code snippets on a single page.', 'https://storage.googleapis.com/hackersandslackers-cdn/2019/03/jquery-2-2.jpg', 5);
insert into resources (title, url, description, img_url, created_by) values ('Arrow Function Video', 'https://www.youtube.com/watch?v=6sQDTgOqh-I', 'Great video about how arrow functions work and when to use them.', 'https://hackernoon.com/hn-images/1*03y1jp5rJOkrpd3EZmO7aQ.jpeg', 5);
insert into resources (title, url, description, img_url, created_by) values ('Online Graphing Calculator', 'https://www.desmos.com/scientific', 'The best online scientific calculator out there!.', 'https://i.ytimg.com/vi/bFYeJd4_TAM/maxresdefault.jpg', 5);
insert into resources (title, url, description, img_url, created_by) values ('OpenSource 3D Chemical Model App', 'http://molview.org/', 'A structural formula editor and 3D model viewer bound to help any student better visualize chemical compounds and concepts', 'https://lh3.googleusercontent.com/ZoOrlwEPieLQx7q2E5Kv2s5SG6bg9CRpizX1ZOk5szDwk8QBpRbfwQiXw9NlixiBktAKh8EuuA=w640-h400-e365', 5);
insert into resources (title, url, description, img_url, created_by) values ('Projectile Motion Tutorial with Examples', 'https://www.youtube.com/watch?v=B83c9IHSR3s', 'This physics video tutorial focuses on how to solve projectile motion problems in two dimensions using kinematic equations.', 'https://i.ytimg.com/vi/B83c9IHSR3s/maxresdefault.jpg', 5);
insert into resources (title, url, description, img_url, created_by) values ('Musical Lecture on the Krebs Cycle', 'https://www.youtube.com/watch?v=JPCs5pn7UNI', 'An overview of the Krebs Cycle, sung to a reggae beat (seriously!), over 1 million views!!', 'https://i.ytimg.com/vi/JPCs5pn7UNI/maxresdefault.jpg', 5);
insert into resources (title, url, description, img_url, created_by) values ('The Physics Classroom', 'https://www.physicsclassroom.com/about', 'The Physics Classroom is an online, free to use physics website developed primarily for beginning physics students and their teachers.', 'https://d1e2bohyu2u2w9.cloudfront.net/education/sites/default/files/experience-media-file/physics_classroom_1.png?width=660&height=415&iframe=1&slide=0&scalePhotos=1', 5);
insert into resources (title, url, description, img_url, created_by) values ('Dimensional Analysis Video Tutorial', 'https://www.youtube.com/watch?v=d_WfCwJW0Og', 'This is an instructional video on how to use two easy steps to answer dimensional analysis problems', 'https://i.ytimg.com/vi/d_WfCwJW0Og/maxresdefault.jpg', 5);

